
<?
echo("
<option>Санкт-Петербург</option>
<option>Москва</option>
<option>Алматы</option>
<option>Архангельск</option>
<option>Астрахань</option>
<option>Баку</option>
<option>Владимир</option>
<option>Волгоград</option>
<option>Воронеж</option>
<option>Всеволожск</option>
<option>Екатеринбург</option>
<option>Зеленоград</option>
<option>Казань</option>
<option>Комсомольск-на-Амуре</option>
<option>Красноярск</option>
<option>Мурино</option>
<option>Нижний Новгород</option>
<option>Новополоцк</option>
<option>Новосибирск</option>
<option>Новочеркасск</option>
<option>Петрозаводск</option>
<option>Подольск</option>
<option>Самара</option>
<option>Саранск</option>
<option>Саратов</option>
<option>Симферополь</option>
<option>Таганрог</option>
<option>Тамбов</option>
<option>Томск</option>
<option>Тосно</option>
<option>Улан-Удэ</option>
<option>Уфа</option>
<option>Хабаровск</option>
<option>Челябинск</option>
");
?>